version: "3.4"

services:
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql

  mariadb:
    image: mariadb:10.5
    ports:
      - 3309:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mariadb:/var/lib/mysql

  postgre:
    image: postgres:12.4
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: pg_bench

  yugabytedb:
    image: yugabytedb/yugabyte:latest
    entrypoint: ["yugabyted", "start", "--daemon=false", "--callhome=false"]
    ulimits:
      nofile: 64000
    ports:
      - 5433:5433
    volumes:
      - yugabytedb:/home/yugabyte/var

volumes:
  mysql:
  mongo:
  mariadb:
  postgre:
  yugabytedb:
